import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import GlobalHeader from '@/app/components/layout/GlobalHeader';
import GlobalNavigation from '@/app/components/layout/GlobalNavigation';
import GlobalFooter from '@/app/components/layout/GlobalFooter';

import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="contentsWrapper">
          <div className="contentsNav">
            <GlobalHeader />
            <GlobalNavigation />
          </div>
          <div className="coontentsBody">
            {children}
            <GlobalFooter />
          </div>
        </div>
      </body>
    </html>
  )
}
